# Generated by Django 5.2.6 on 2025-09-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='evidence/'),
        ),
    ]
