# Generated by Django 5.2.6 on 2025-09-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_achievement_evidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='evidence_file',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.faculty'),
        ),
    ]
