# Generated by Django 5.2.6 on 2025-09-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_achievement_evidence_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
        migrations.AlterField(
            model_name='departments',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
