# Generated by Django 5.2.6 on 2025-09-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_portfolio_url_alter_departments_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='evidence_file',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='evidence_url',
        ),
    ]
