# Generated by Django 5.2.6 on 2025-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_achievement_evidence_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='evidence_file',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='evidence_url',
            field=models.URLField(blank=True),
        ),
    ]
