# Generated by Django 5.2.6 on 2025-09-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_achievement_evidence_file_achievement_evidence_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='evidence_file',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='evidence_url',
        ),
    ]
